/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AddMovieMethod {
    #[serde(rename = "manual")]
    Manual,
    #[serde(rename = "list")]
    List,
    #[serde(rename = "collection")]
    Collection,

}

impl ToString for AddMovieMethod {
    fn to_string(&self) -> String {
        match self {
            Self::Manual => String::from("manual"),
            Self::List => String::from("list"),
            Self::Collection => String::from("collection"),
        }
    }
}

impl Default for AddMovieMethod {
    fn default() -> AddMovieMethod {
        Self::Manual
    }
}




