/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApplyTags {
    #[serde(rename = "add")]
    Add,
    #[serde(rename = "remove")]
    Remove,
    #[serde(rename = "replace")]
    Replace,

}

impl ToString for ApplyTags {
    fn to_string(&self) -> String {
        match self {
            Self::Add => String::from("add"),
            Self::Remove => String::from("remove"),
            Self::Replace => String::from("replace"),
        }
    }
}

impl Default for ApplyTags {
    fn default() -> ApplyTags {
        Self::Add
    }
}




