/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuthenticationRequiredType {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabledForLocalAddresses")]
    DisabledForLocalAddresses,

}

impl ToString for AuthenticationRequiredType {
    fn to_string(&self) -> String {
        match self {
            Self::Enabled => String::from("enabled"),
            Self::DisabledForLocalAddresses => String::from("disabledForLocalAddresses"),
        }
    }
}

impl Default for AuthenticationRequiredType {
    fn default() -> AuthenticationRequiredType {
        Self::Enabled
    }
}




