/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BackupType {
    #[serde(rename = "scheduled")]
    Scheduled,
    #[serde(rename = "manual")]
    Manual,
    #[serde(rename = "update")]
    Update,

}

impl ToString for BackupType {
    fn to_string(&self) -> String {
        match self {
            Self::Scheduled => String::from("scheduled"),
            Self::Manual => String::from("manual"),
            Self::Update => String::from("update"),
        }
    }
}

impl Default for BackupType {
    fn default() -> BackupType {
        Self::Scheduled
    }
}




