/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CertificateValidationType {
    #[serde(rename = "enabled")]
    Enabled,
    #[serde(rename = "disabledForLocalAddresses")]
    DisabledForLocalAddresses,
    #[serde(rename = "disabled")]
    Disabled,

}

impl ToString for CertificateValidationType {
    fn to_string(&self) -> String {
        match self {
            Self::Enabled => String::from("enabled"),
            Self::DisabledForLocalAddresses => String::from("disabledForLocalAddresses"),
            Self::Disabled => String::from("disabled"),
        }
    }
}

impl Default for CertificateValidationType {
    fn default() -> CertificateValidationType {
        Self::Enabled
    }
}




