/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CommandPriority {
    #[serde(rename = "normal")]
    Normal,
    #[serde(rename = "high")]
    High,
    #[serde(rename = "low")]
    Low,

}

impl ToString for CommandPriority {
    fn to_string(&self) -> String {
        match self {
            Self::Normal => String::from("normal"),
            Self::High => String::from("high"),
            Self::Low => String::from("low"),
        }
    }
}

impl Default for CommandPriority {
    fn default() -> CommandPriority {
        Self::Normal
    }
}




