/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CommandStatus {
    #[serde(rename = "queued")]
    Queued,
    #[serde(rename = "started")]
    Started,
    #[serde(rename = "completed")]
    Completed,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "aborted")]
    Aborted,
    #[serde(rename = "cancelled")]
    Cancelled,
    #[serde(rename = "orphaned")]
    Orphaned,

}

impl ToString for CommandStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Queued => String::from("queued"),
            Self::Started => String::from("started"),
            Self::Completed => String::from("completed"),
            Self::Failed => String::from("failed"),
            Self::Aborted => String::from("aborted"),
            Self::Cancelled => String::from("cancelled"),
            Self::Orphaned => String::from("orphaned"),
        }
    }
}

impl Default for CommandStatus {
    fn default() -> CommandStatus {
        Self::Queued
    }
}




