/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum CreditType {
    #[serde(rename = "cast")]
    Cast,
    #[serde(rename = "crew")]
    Crew,

}

impl ToString for CreditType {
    fn to_string(&self) -> String {
        match self {
            Self::Cast => String::from("cast"),
            Self::Crew => String::from("crew"),
        }
    }
}

impl Default for CreditType {
    fn default() -> CreditType {
        Self::Cast
    }
}




