/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FileDateType {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "cinemas")]
    Cinemas,
    #[serde(rename = "release")]
    Release,

}

impl ToString for FileDateType {
    fn to_string(&self) -> String {
        match self {
            Self::None => String::from("none"),
            Self::Cinemas => String::from("cinemas"),
            Self::Release => String::from("release"),
        }
    }
}

impl Default for FileDateType {
    fn default() -> FileDateType {
        Self::None
    }
}




