/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImportListConfigResource {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "listSyncLevel", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub list_sync_level: Option<Option<String>>,
    #[serde(rename = "importExclusions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub import_exclusions: Option<Option<String>>,
}

impl ImportListConfigResource {
    pub fn new() -> ImportListConfigResource {
        ImportListConfigResource {
            id: None,
            list_sync_level: None,
            import_exclusions: None,
        }
    }
}


