/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MediaCoverTypes {
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "poster")]
    Poster,
    #[serde(rename = "banner")]
    Banner,
    #[serde(rename = "fanart")]
    Fanart,
    #[serde(rename = "screenshot")]
    Screenshot,
    #[serde(rename = "headshot")]
    Headshot,
    #[serde(rename = "clearlogo")]
    Clearlogo,

}

impl ToString for MediaCoverTypes {
    fn to_string(&self) -> String {
        match self {
            Self::Unknown => String::from("unknown"),
            Self::Poster => String::from("poster"),
            Self::Banner => String::from("banner"),
            Self::Fanart => String::from("fanart"),
            Self::Screenshot => String::from("screenshot"),
            Self::Headshot => String::from("headshot"),
            Self::Clearlogo => String::from("clearlogo"),
        }
    }
}

impl Default for MediaCoverTypes {
    fn default() -> MediaCoverTypes {
        Self::Unknown
    }
}




