/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MovieHistoryEventType {
    #[serde(rename = "unknown")]
    Unknown,
    #[serde(rename = "grabbed")]
    Grabbed,
    #[serde(rename = "downloadFolderImported")]
    DownloadFolderImported,
    #[serde(rename = "downloadFailed")]
    DownloadFailed,
    #[serde(rename = "movieFileDeleted")]
    MovieFileDeleted,
    #[serde(rename = "movieFolderImported")]
    MovieFolderImported,
    #[serde(rename = "movieFileRenamed")]
    MovieFileRenamed,
    #[serde(rename = "downloadIgnored")]
    DownloadIgnored,

}

impl ToString for MovieHistoryEventType {
    fn to_string(&self) -> String {
        match self {
            Self::Unknown => String::from("unknown"),
            Self::Grabbed => String::from("grabbed"),
            Self::DownloadFolderImported => String::from("downloadFolderImported"),
            Self::DownloadFailed => String::from("downloadFailed"),
            Self::MovieFileDeleted => String::from("movieFileDeleted"),
            Self::MovieFolderImported => String::from("movieFolderImported"),
            Self::MovieFileRenamed => String::from("movieFileRenamed"),
            Self::DownloadIgnored => String::from("downloadIgnored"),
        }
    }
}

impl Default for MovieHistoryEventType {
    fn default() -> MovieHistoryEventType {
        Self::Unknown
    }
}




