/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct NamingConfigResource {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "renameMovies", skip_serializing_if = "Option::is_none")]
    pub rename_movies: Option<bool>,
    #[serde(rename = "replaceIllegalCharacters", skip_serializing_if = "Option::is_none")]
    pub replace_illegal_characters: Option<bool>,
    #[serde(rename = "colonReplacementFormat", skip_serializing_if = "Option::is_none")]
    pub colon_replacement_format: Option<crate::models::ColonReplacementFormat>,
    #[serde(rename = "standardMovieFormat", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub standard_movie_format: Option<Option<String>>,
    #[serde(rename = "movieFolderFormat", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub movie_folder_format: Option<Option<String>>,
    #[serde(rename = "includeQuality", skip_serializing_if = "Option::is_none")]
    pub include_quality: Option<bool>,
    #[serde(rename = "replaceSpaces", skip_serializing_if = "Option::is_none")]
    pub replace_spaces: Option<bool>,
    #[serde(rename = "separator", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub separator: Option<Option<String>>,
    #[serde(rename = "numberStyle", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub number_style: Option<Option<String>>,
}

impl NamingConfigResource {
    pub fn new() -> NamingConfigResource {
        NamingConfigResource {
            id: None,
            rename_movies: None,
            replace_illegal_characters: None,
            colon_replacement_format: None,
            standard_movie_format: None,
            movie_folder_format: None,
            include_quality: None,
            replace_spaces: None,
            separator: None,
            number_style: None,
        }
    }
}


