/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PrivacyLevel {
    #[serde(rename = "normal")]
    Normal,
    #[serde(rename = "password")]
    Password,
    #[serde(rename = "apiKey")]
    ApiKey,
    #[serde(rename = "userName")]
    UserName,

}

impl ToString for PrivacyLevel {
    fn to_string(&self) -> String {
        match self {
            Self::Normal => String::from("normal"),
            Self::Password => String::from("password"),
            Self::ApiKey => String::from("apiKey"),
            Self::UserName => String::from("userName"),
        }
    }
}

impl Default for PrivacyLevel {
    fn default() -> PrivacyLevel {
        Self::Normal
    }
}




