/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProperDownloadTypes {
    #[serde(rename = "preferAndUpgrade")]
    PreferAndUpgrade,
    #[serde(rename = "doNotUpgrade")]
    DoNotUpgrade,
    #[serde(rename = "doNotPrefer")]
    DoNotPrefer,

}

impl ToString for ProperDownloadTypes {
    fn to_string(&self) -> String {
        match self {
            Self::PreferAndUpgrade => String::from("preferAndUpgrade"),
            Self::DoNotUpgrade => String::from("doNotUpgrade"),
            Self::DoNotPrefer => String::from("doNotPrefer"),
        }
    }
}

impl Default for ProperDownloadTypes {
    fn default() -> ProperDownloadTypes {
        Self::PreferAndUpgrade
    }
}




