/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProviderMessageType {
    #[serde(rename = "info")]
    Info,
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "error")]
    Error,

}

impl ToString for ProviderMessageType {
    fn to_string(&self) -> String {
        match self {
            Self::Info => String::from("info"),
            Self::Warning => String::from("warning"),
            Self::Error => String::from("error"),
        }
    }
}

impl Default for ProviderMessageType {
    fn default() -> ProviderMessageType {
        Self::Info
    }
}




