/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ProxyType {
    #[serde(rename = "http")]
    Http,
    #[serde(rename = "socks4")]
    Socks4,
    #[serde(rename = "socks5")]
    Socks5,

}

impl ToString for ProxyType {
    fn to_string(&self) -> String {
        match self {
            Self::Http => String::from("http"),
            Self::Socks4 => String::from("socks4"),
            Self::Socks5 => String::from("socks5"),
        }
    }
}

impl Default for ProxyType {
    fn default() -> ProxyType {
        Self::Http
    }
}




