/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RatingType {
    #[serde(rename = "user")]
    User,
    #[serde(rename = "critic")]
    Critic,

}

impl ToString for RatingType {
    fn to_string(&self) -> String {
        match self {
            Self::User => String::from("user"),
            Self::Critic => String::from("critic"),
        }
    }
}

impl Default for RatingType {
    fn default() -> RatingType {
        Self::User
    }
}




