/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RescanAfterRefreshType {
    #[serde(rename = "always")]
    Always,
    #[serde(rename = "afterManual")]
    AfterManual,
    #[serde(rename = "never")]
    Never,

}

impl ToString for RescanAfterRefreshType {
    fn to_string(&self) -> String {
        match self {
            Self::Always => String::from("always"),
            Self::AfterManual => String::from("afterManual"),
            Self::Never => String::from("never"),
        }
    }
}

impl Default for RescanAfterRefreshType {
    fn default() -> RescanAfterRefreshType {
        Self::Always
    }
}




