/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RuntimeMode {
    #[serde(rename = "console")]
    Console,
    #[serde(rename = "service")]
    Service,
    #[serde(rename = "tray")]
    Tray,

}

impl ToString for RuntimeMode {
    fn to_string(&self) -> String {
        match self {
            Self::Console => String::from("console"),
            Self::Service => String::from("service"),
            Self::Tray => String::from("tray"),
        }
    }
}

impl Default for RuntimeMode {
    fn default() -> RuntimeMode {
        Self::Console
    }
}




