/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SortDirection {
    #[serde(rename = "default")]
    Default,
    #[serde(rename = "ascending")]
    Ascending,
    #[serde(rename = "descending")]
    Descending,

}

impl ToString for SortDirection {
    fn to_string(&self) -> String {
        match self {
            Self::Default => String::from("default"),
            Self::Ascending => String::from("ascending"),
            Self::Descending => String::from("descending"),
        }
    }
}

impl Default for SortDirection {
    fn default() -> SortDirection {
        Self::Default
    }
}




