/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TrackedDownloadStatus {
    #[serde(rename = "ok")]
    Ok,
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "error")]
    Error,

}

impl ToString for TrackedDownloadStatus {
    fn to_string(&self) -> String {
        match self {
            Self::Ok => String::from("ok"),
            Self::Warning => String::from("warning"),
            Self::Error => String::from("error"),
        }
    }
}

impl Default for TrackedDownloadStatus {
    fn default() -> TrackedDownloadStatus {
        Self::Ok
    }
}




