/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum TrackedDownloadState {
    #[serde(rename = "downloading")]
    Downloading,
    #[serde(rename = "importPending")]
    ImportPending,
    #[serde(rename = "importing")]
    Importing,
    #[serde(rename = "imported")]
    Imported,
    #[serde(rename = "failedPending")]
    FailedPending,
    #[serde(rename = "failed")]
    Failed,
    #[serde(rename = "ignored")]
    Ignored,

}

impl ToString for TrackedDownloadState {
    fn to_string(&self) -> String {
        match self {
            Self::Downloading => String::from("downloading"),
            Self::ImportPending => String::from("importPending"),
            Self::Importing => String::from("importing"),
            Self::Imported => String::from("imported"),
            Self::FailedPending => String::from("failedPending"),
            Self::Failed => String::from("failed"),
            Self::Ignored => String::from("ignored"),
        }
    }
}

impl Default for TrackedDownloadState {
    fn default() -> TrackedDownloadState {
        Self::Downloading
    }
}




