/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UpdateMechanism {
    #[serde(rename = "builtIn")]
    BuiltIn,
    #[serde(rename = "script")]
    Script,
    #[serde(rename = "external")]
    External,
    #[serde(rename = "apt")]
    Apt,
    #[serde(rename = "docker")]
    Docker,

}

impl ToString for UpdateMechanism {
    fn to_string(&self) -> String {
        match self {
            Self::BuiltIn => String::from("builtIn"),
            Self::Script => String::from("script"),
            Self::External => String::from("external"),
            Self::Apt => String::from("apt"),
            Self::Docker => String::from("docker"),
        }
    }
}

impl Default for UpdateMechanism {
    fn default() -> UpdateMechanism {
        Self::BuiltIn
    }
}




