/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Version {
    #[serde(rename = "major", skip_serializing_if = "Option::is_none")]
    pub major: Option<i32>,
    #[serde(rename = "minor", skip_serializing_if = "Option::is_none")]
    pub minor: Option<i32>,
    #[serde(rename = "build", skip_serializing_if = "Option::is_none")]
    pub build: Option<i32>,
    #[serde(rename = "revision", skip_serializing_if = "Option::is_none")]
    pub revision: Option<i32>,
    #[serde(rename = "majorRevision", skip_serializing_if = "Option::is_none")]
    pub major_revision: Option<i32>,
    #[serde(rename = "minorRevision", skip_serializing_if = "Option::is_none")]
    pub minor_revision: Option<i32>,
}

impl Version {
    pub fn new() -> Version {
        Version {
            major: None,
            minor: None,
            build: None,
            revision: None,
            major_revision: None,
            minor_revision: None,
        }
    }
}


